### ISSUE TITLE
install

### ISSUE THREAD

**Issue by asisoft007** [abhijeetgupta1988/nopcommerce-payu-money-india#3]
i have issue on install plugin in nopcommerce website 

i have done upload plugin but then i in installed on website 

its show install but then not show in plugin list then referesh site 

after refersh show the website install 
[issue in website plz resolve.docx](https://github.com/abhijeetgupta1988/nopcommerce-payu-money-india/files/7616511/issue.in.website.plz.resolve.docx)

**Comment by jhakasjk** [comment]
Payments.Payu: The main assembly isn't found. Hence this plugin can't be loaded.
