### ISSUE TITLE
Installation error: No descriptor file is found. It should be in the root of the archive.

### ISSUE THREAD

**Issue by balajivelu147** [abhijeetgupta1988/nopcommerce-payu-money-india#4]
while uploading the zip file, it fails saying this error

No descriptor file is found. It should be in the root of the archive, please help me fix it

nop version: 4.50
azure hosting

**Comment by jhakasjk** [comment]
Payments.Payu: The main assembly isn't found. Hence this plugin can't be loaded.
I am using v4.8
<img width="1529" height="663" alt="Image" src="https://github.com/user-attachments/assets/5e46501c-cf40-410d-9693-abace50eaf08" />
